<?php
/**
 * @file
 * Code for the manatime_feature_clients feature.
 */

include_once 'manatime_feature_clients.features.inc';

/**
 * Implements hook_permission().
 */
function manatime_feature_clients_permission() {
  return array(
    'manage clients' => array(
      'title' => t('Manage clients'),
      'description' => t('Allow add, archive and edit clients.'),
    ),
  );
}

/**
 * Implements hook_action_info().
 */
function manatime_feature_clients_action_info() {
  return array(
    'manatime_feature_clients_action_enable' => array(
      'type' => 'entity',
      'label' => t('Activate Clients'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'manatime_feature_clients_action_disable' => array(
      'type' => 'entity',
      'label' => t('Deactivate Clients'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Enable clients.
 */
function manatime_feature_clients_action_enable(&$entity, $context) {
  $entity->field_active[LANGUAGE_NONE][0]['value'] = 1;
}

/**
 * Disable clients.
 */
function manatime_feature_clients_action_disable(&$entity, $context) {
  $entity->field_active[LANGUAGE_NONE][0]['value'] = 0;
}
