<?php
/**
 * @file
 * Code for the Manatime users feature feature.
 */

include_once 'manatime_feature_users.features.inc';

/**
 * Implements hook_action_info().
 */
function manatime_feature_users_action_info() {
  return array(
    'manatime_feature_users_action_enable' => array(
      'type' => 'entity',
      'label' => t('Activate Users'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'manatime_feature_users_action_disable' => array(
      'type' => 'entity',
      'label' => t('Deactivate Users'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Enable users.
 */
function manatime_feature_users_action_enable(&$entity, $context) {
  $entity->status['value'] = 1;
}

/**
 * Disable users.
 */
function manatime_feature_users_action_disable(&$entity, $context) {
  $entity->status['value'] = 0;
}
